 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/current_members", type: :request do
  
  # CurrentMember. As you add validations to CurrentMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CurrentMember.create! valid_attributes
      get current_members_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      current_member = CurrentMember.create! valid_attributes
      get current_member_url(current_member)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_current_member_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      current_member = CurrentMember.create! valid_attributes
      get edit_current_member_url(current_member)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CurrentMember" do
        expect {
          post current_members_url, params: { current_member: valid_attributes }
        }.to change(CurrentMember, :count).by(1)
      end

      it "redirects to the created current_member" do
        post current_members_url, params: { current_member: valid_attributes }
        expect(response).to redirect_to(current_member_url(CurrentMember.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CurrentMember" do
        expect {
          post current_members_url, params: { current_member: invalid_attributes }
        }.to change(CurrentMember, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post current_members_url, params: { current_member: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested current_member" do
        current_member = CurrentMember.create! valid_attributes
        patch current_member_url(current_member), params: { current_member: new_attributes }
        current_member.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the current_member" do
        current_member = CurrentMember.create! valid_attributes
        patch current_member_url(current_member), params: { current_member: new_attributes }
        current_member.reload
        expect(response).to redirect_to(current_member_url(current_member))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        current_member = CurrentMember.create! valid_attributes
        patch current_member_url(current_member), params: { current_member: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested current_member" do
      current_member = CurrentMember.create! valid_attributes
      expect {
        delete current_member_url(current_member)
      }.to change(CurrentMember, :count).by(-1)
    end

    it "redirects to the current_members list" do
      current_member = CurrentMember.create! valid_attributes
      delete current_member_url(current_member)
      expect(response).to redirect_to(current_members_url)
    end
  end
end
